### ISSUE TITLE
StackOverflow when running CodeChicken core in a dev env

### ISSUE THREAD

**Issue by cpw** [TheCBProject/CodeChickenCore#18]
Hitting a StackOverflow in PacketCustom when trying to open a translocator gui while debugging its interaction in a dev env. I have done the *standard* mechanism of adding codechicken core/lib and translocators to the mods dir of my dev env. This deobfuscates the code to my current MCP naming. It looks like this is not compatible with your coremod functionality and is in fact, breaking the class files in memory. I am not willing to create a strong dep to codechicken to debug this interaction.

**Comment by covers1624** [comment]
Ah, this is due to MCP mappings and CCL, CCL has some methods named the same in PacketCustom as the new mappings in PacketBuffer. Ran in to this in 1.11, decided to drop PacketBuffer support and wrap ByteBuff directly as PacketCustom basically does the same thing except is way more flexible. Ill see about doing the same thing in 1.10, but i may break binary compat.

**Comment by LatvianModder** [comment]
Or, you know, you could just use intended SimpleNetworkWrapper and IMessages...

**Comment by covers1624** [comment]
Err, No, I don't like that system and really dont want to rewrite all of the packet handling code in everything. Plus the need for 2 classes per packet is kinda dumb. The issue in question has no actual impact at runtime only in dev due to overlaping names with MCP and has been resolved in 1.11.

**Comment by covers1624** [comment]
Gonna close this as it is an issue of too newer MCP mappings, belongs with CCL and has been resolved in 1.11
